language: cpp
compiler: gcc
sudo: required
dist: trusty

before_install:
 - cmake -G "Unix Makefiles"
 - sudo make install
 - flappy --help
 - flappy -h
 - flappy help
 - flappy help init
 - flappy help gentarget
 - flappy help prebuild
 - flappy init testproject
 - cd testproject
 - flappy prebuild qt
 - flappy prebuild cmake
 - flappy prebuild ios
 - flappy prebuild android
 - flappy prebuild web
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq gcc-5 g++-5
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
 - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base libglew-dev mesa-common-dev freeglut3-dev

script:
 - cd targets/qt
 - qmake testproject.pro
 - make
 - cd ../../

after_success:
  - cd ../
  - sudo make uninstall
