#!/usr/bin/python
import os
import sys
import json
import importlib

import tools

if len(sys.argv) > 1:
    command = sys.argv[1]
    if command == "--help" or command == "-h":
        command = "help"
else:
    command = "help"

proRoot = tools.findProRoot(".")
configPath = ""
config = None
if proRoot is not None:
    configPath = os.path.join(proRoot, "config.json")
    jsonFile = open(configPath, 'r')
    config = tools.parseConfig(json.load(jsonFile))


toolPath = tools.getToolPath(sys.argv[0])

if proRoot:
    tools.infoMessage("info", "Project root: " + proRoot)
tools.infoMessage("info", "FlappyTools: " + toolPath)

importlib.import_module(command).run(sys.argv[1:],
                                     proRoot,
                                     toolPath,
                                     config)
